#!/bin/bash
#Deployment script for TreeCage.  Run this at the root of the project (same location as www dir)
read -p "Root URL: " ROOT
cat <<<"SetEnv APPROOT $PWD
SetEnv ROOT $ROOT" > public/.htaccess
